name: Coderrect Scan
description: >
  Coderrect detects concurrency bugs and multithreading errors in multithreaded programs (e.g., data races, race conditions).
branding:
  icon: check
  color: green
inputs:
  buildCommand:
    description: "Custom build command"
    required: false
    default: "make -j"
  cleanCommand:
    description: "Custom clean command"
    required: false
    default: "make clean || true"
  buildPath:
    description: "The relative path for your build directory"
    required: false
    default: "."
  options:
    description: "Command line options for Coderrect Scanner"
    required: false
    default: "-analyzeAllBinaries"
  exit0:
    description: "Force Coderrect to exit with 0 even when races are detected"
    required: false
    default: false
runs:
  using: composite
  steps:
    - run: | 
        wget -q https://public-installer-pkg.s3.us-east-2.amazonaws.com/coderrect-linux-develop.tar.gz
        tar zxf coderrect-linux-develop.tar.gz
        echo "$PWD/coderrect-linux-develop/bin" >> $GITHUB_PATH
        cd ${{ inputs.buildPath }}
        ${{ inputs.cleanCommand }}
      shell: bash
    - run: |
        cd ${{ inputs.buildPath }}
        coderrect -noprogress ${{ inputs.options }} ${{ inputs.buildCommand }}
      shell: bash
    - run: |
        cd ${{ inputs.buildPath }}
        coderrect -publish.cloud="DEFAULT" -publish.exit0=${{ inputs.exit0 }}
      shell: bash
